name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v3

      - name: Create Firebase Config ðŸ¤«
        run: |
          echo "const firebaseConfig = {" > firebase-config.js
          echo "  apiKey: \"${{ secrets.API_KEY }}\"," >> firebase-config.js
          echo "  authDomain: \"${{ secrets.AUTH_DOMAIN }}\"," >> firebase-config.js
          echo "  databaseURL: \"${{ secrets.DATABASE_URL }}\"," >> firebase-config.js
          echo "  projectId: \"${{ secrets.PROJECT_ID }}\"," >> firebase-config.js
          echo "  storageBucket: \"${{ secrets.STORAGE_BUCKET }}\"," >> firebase-config.js
          echo "  messagingSenderId: \"${{ secrets.MESSAGING_SENDER_ID }}\"," >> firebase-config.js
          echo "  appId: \"${{ secrets.APP_ID }}\"," >> firebase-config.js
          echo "  measurementId: \"${{ secrets.MEASUREMENT_ID }}\"" >> firebase-config.js
          echo "};" >> firebase-config.js
          echo "" >> firebase-config.js
          echo "// Initialize Firebase" >> firebase-config.js
          echo "firebase.initializeApp(firebaseConfig);" >> firebase-config.js

      - name: Deploy to gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git init -b gh-pages
          git add -A
          git commit -m "Deploy to GitHub Pages"
          git push --force "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" gh-pages